GestionEcole/GestionEcole/Controllers/EtudiantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestionEcole.Models;

namespace GestionEcole.Controllers
{
    public class EtudiantController : Controller
    {
        private EcoleContainer DB = new EcoleContainer();



        #region Affichage de la liste d'etudiant

        private int nbElement = 7;
        //
        // GET: /Etudiant/
        /// <summary>
        /// Affichage d'une vue selon un certain nombre d'etudiants par page
        /// </summary>
        /// <param name="numPage">Le numero de la page</param>
        /// 
        /// <returns>Une liste d'etudiants</returns>
        [AllowAnonymous]
        public ActionResult Index(int numPage = 0)
        {
            var lstEtud = (from e in DB.Etudiants
                           select e).ToList();

            var lstPage = (from e in DB.Etudiants
                           select e).OrderBy(e => e.Id).Skip(nbElement * numPage).Take(nbElement).ToList();


            ViewBag.CombienDePage = lstEtud.Count / nbElement;

            return View(lstPage);
        }
        #endregion

        #region Detail de l'Etudiant
        // GET: /Etudiant/Details/5

        /// <summary>
        /// Affichage du detail des etudiants
        /// </summary>
        /// <param name="id"> id de l'etudiant</param>
        /// <returns> La page de detail d'un etudiant donné</returns>
        public ActionResult Details(int id)
        {
            Etudiant etudiant = (from e in DB.Etudiants
                                 where e.Id == id
                                 select e).First();
            if (User.Identity.Name == etudiant.Email || User.IsInRole("Admin") || User.IsInRole("Enseignant"))
            {


                // les presences de cours d un etudiant
                var presencesAucours = (from pc in DB.PresenceCours
                                        where pc.EtudiantId == id
                                        select pc).ToList();

                var coursEtudiant = presencesAucours.Select(pc => pc.Cours).ToList();
                var matiereEtudiant = coursEtudiant.Select(mt => mt.Matiere).ToList();

                ViewBag.coursEtudiant = coursEtudiant;

                ViewBag.matiereEtudiant = matiereEtudiant;

                var sommeNotes = etudiant.Evaluations.Sum(e => e.Note);
                var sumPonderation = etudiant.Evaluations.Sum(e => e.TypeEvaluation.Ponderation);


                decimal Moyenne;

                if (sumPonderation != 0)
                {
                    Moyenne = (sommeNotes / sumPonderation) * 100;

                    etudiant.Moyenne = decimal.Round(Moyenne, 2);

                }

                return View(etudiant);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region Creation de l'Etudiant
        // GET: /Etudiant/Create
        /// <summary>
        /// Retoure la vue de creation d'un etudiant
        /// </summary>
        /// <returns>Vue de creation</returns>

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }


        // POST: /Etudiant/Create
        /// <summary>
        /// Creation d'un etudiant dans la base de donnee
        /// </summary>
        /// <param name="NouvEtudiant"> Le nouveau Etudiant a creer </param>
        /// <returns>La vue Index des etudiants si la creation est valider sinon la vue de la creation</returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Etudiant NouvEtudiant)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    int c = (from e in DB.Etudiants
                             where e.Email.Equals(NouvEtudiant.Email)
                             select e).Count();

                    if (c > 0)
                    {
                        ModelState.AddModelError("Email", "Email existe deja!");
                    }

                    else
                    {
                        DB.Etudiants.Add(NouvEtudiant);

                        DB.SaveChanges();

                        return RedirectToAction("Index");
                    }
                }

                {
                    return View();
                }

            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Edition un Etudiant
        // GET: /Etudiant/Edit/5
        /// <summary>
        /// Affichage de l'etudiant a editer
        /// </summary>
        /// <param name="id"> L'id de l'etudiant a editer</param>
        /// <returns> la vue des etudiants</returns>
        /// 
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Etudiant etudiant = (from e in DB.Etudiants
                                 where e.Id == id
                                 select e).First();

            return View(etudiant);
        }


        // POST: /Etudiant/Edit/5
        /// <summary>
        /// Edition d'un etudiant et l'enregistrer dans la base de donnees 
        /// </summary>
        /// <param name="id"> L'id de l'etudiant passer en parametre a editer </param>
        /// <param name="EditEtudiant">L'etudiant editer</param>
        /// <returns> La vue Index des etudiants si l'edition est valider sinon la vue de l'edition</returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, Etudiant EditEtudiant)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    Etudiant etudiant = (from e in DB.Etudiants
                                         where e.Id == id
                                         select e).First();

                    etudiant.Nom = EditEtudiant.Nom;
                    etudiant.Prenom = EditEtudiant.Prenom;
                    etudiant.Email = EditEtudiant.Email;
                    etudiant.DateNaissance = EditEtudiant.DateNaissance;
                    etudiant.Adresse = EditEtudiant.Adresse;
                    etudiant.Photo = EditEtudiant.Photo;

                    DB.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region Suppression un Etudiant
        //
        // GET: /Etudiant/Delete/5
        /// <summary>
        ///  Affichage de la vue de suppression d'un etudiant
        /// </summary>
        /// <param name="id"> L'id de l'etudiant a supprimer</param>
        /// <returns> La vue de suppression d'un etudiant</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Etudiant etudiant = (from e in DB.Etudiants
                                 where e.Id == id
                                 select e).First();

            return View(etudiant);
        }

        //
        // POST: /Etudiant/Delete/5
        /// <summary>
        /// Suppression de la base de donnee d'un etudiant donnee
        /// </summary>
        /// <param name="id">L'id de l'etudiant a supprimer </param>
        /// <param name="collection">Le formulaire d'un etudiant</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                Etudiant etudiant = (from e in DB.Etudiants
                                     where e.Id == id
                                     select e).First();

                DB.Etudiants.Remove(etudiant);
                DB.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region fermeture de la page
        protected override void Dispose(bool disposing)
        {
            DB.Dispose();
            base.Dispose(disposing);
        }
        #endregion

    }
}

GestionEcole/GestionEcole/Controllers/HomeController.cs
using GestionEcole.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionEcole.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GestionEcole/GestionEcole/Controllers/MatiereController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestionEcole.Models;

namespace GestionEcole.Controllers
{
    public class MatiereController : Controller
    {
        private EcoleContainer DB = new EcoleContainer();


        #region Affichage de la liste des matieres

        private int nbElement = 7;
        //
        // GET: /Matiere/
        /// <summary>
        ///Affichage d'une vue selon un certain nombre de matiere par page
        /// </summary>
        /// <param name="numPage">Le numero de la page</param>
        /// <returns>une Liste de matiere</returns>
        public ActionResult Index(int numPage = 0)
        {
            List<Matiere> LstMatieres = (from m in DB.Matieres
                                         select m).ToList();

            List<Matiere> LstPage = (from m in DB.Matieres
                                     select m).OrderBy(m => m.MatiereId)
                                         .Skip(numPage * nbElement).
                                         Take(nbElement).ToList();



            ViewBag.CombienDePage = LstMatieres.Count / nbElement;



            return View(LstPage);
        }

        #endregion

        #region Detail de la matiere
        //
        // GET: /Matiere/Details/5
        /// <summary>
        /// Afficher les details d'une matiere donnee
        /// </summary>
        /// <param name="id"> l'id d'une matiere donnee</param>
        /// <returns>La vue de detail d'une matiere</returns>

        public ActionResult Details(int id, int enseignantId = 0)
        {
            Matiere matiere = (from m in DB.Matieres
                               where m.MatiereId == id
                               select m).First();

            // les evaluations dans une matiere

            var typeEval = matiere.Evaluations.Select(i => i.TypeEvaluation).Distinct().ToList();

            ViewBag.typeEval = typeEval;

            var coursMatiere = matiere.Cours.ToList();
            ViewBag.coursMatiere = coursMatiere;

            if (enseignantId != 0)
            {
                List<Cours> lstCours = (from e in DB.Enseignants
                                        where e.Id == enseignantId
                                        select e).First().Cours.ToList();

                List<Cours> lstCoursInMatiere = (from m in lstCours
                                                 where m.MatiereId == id
                                                 select m).ToList();

                ViewBag.lstCoursInMatiere = lstCoursInMatiere;
            }

            return View(matiere);
        }
        #endregion

        #region Creation d'une matiere
        //
        // GET: /Matiere/Create
        /// <summary>
        /// Affiche la page de creation de matiere
        /// </summary>
        /// <returns> La vue de creation de matiere</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Matiere/Create
        /// <summary>
        /// Creation de la matiere dans la base de donnee
        /// </summary>
        /// <param name="NouvMatiere"> La matiere a creer</param>
        /// <returns>la vue Index des matieres si la creation est valider sinon la vue de la creation</returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Matiere NouvMatiere)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    DB.Matieres.Add(NouvMatiere);

                    DB.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Edition d'une matiere
        //
        // GET: /Matiere/Edit/5
        /// <summary>
        /// Edition d'une matiere donnee
        /// </summary>
        /// <param name="id">L'id de la matiere a editer</param>
        /// <returns>Affichage de la vue de l'edition</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Matiere matiere = (from m in DB.Matieres
                               where m.MatiereId == id
                               select m).First();

            return View(matiere);
        }

        //
        // POST: /Matiere/Edit/5
        /// <summary>
        /// Edition d'une matiere et l'enregistrer dans la base de donnees 
        /// </summary>
        /// <param name="id">L'id de la matiere a editer</param>
        /// <param name="EditMatiere">La matiere Editee</param>
        /// <returns>La vue Index des matieres si l'edition est validee sinon la vue de l'edition</returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, Matiere EditMatiere)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    Matiere matiere = (from m in DB.Matieres
                                       where m.MatiereId == id
                                       select m).First();

                    matiere.Titre = EditMatiere.Titre;
                    matiere.Description = EditMatiere.Description;

                    DB.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Suppresssion d'une matiere
        //
        // GET: /Matiere/Delete/5
        /// <summary>
        /// Affichage de la vue de suppression d'une matiere
        /// </summary>
        /// <param name="id">L'id de la matiere a supprimer</param>
        /// <returns>La vue de suppression d'une matiere</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Matiere matiere = (from m in DB.Matieres
                               where m.MatiereId == id
                               select m).First();

            return View(matiere);
        }

        //
        // POST: /Matiere/Delete/5
        /// <summary>
        /// Suppression de la base de donnee de d'une matiere donnee
        /// </summary>
        /// <param name="id">L'id de la matiere a supprimer</param>
        /// <param name="collection">Le formulaire d'une matiere</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Matiere matiere = (from m in DB.Matieres
                                   where m.MatiereId == id
                                   select m).First();

                DB.Matieres.Remove(matiere);

                DB.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        #endregion



        #region fermeture de page
        protected override void Dispose(bool disposing)
        {
            DB.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

GestionEcole/GestionEcole/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

GestionEcole/GestionEcole/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    
</hgroup>
<div class="col-xs-12">
    <div class="col-xs-6" id="map">


    </div>

    <div class="col-xs-6 text-center">
        <section class="contact">
            <header>
                <h3>Phone</h3>
            </header>
            <p class="">
                <span class="">Tel:</span>
                <span>425.555.0100</span>
            </p>
       
        </section>

        <section class="contact">
            <header>
                <h3>Email</h3>
            </header>
            <p class="">
                <span class="">Contact 1: </span>
                <span><a href="mailto:jihen.arem@gmail.com">jihen.arem@gmail.com</a></span>
            </p>
            <p class="">
                <span class="">Contact 2: </span>
                <span><a href="mailto:cedricgfont@gmail.com">cedricgfont@gmail.comm</a></span>
            </p>

        </section>

        <section class="contact">
            <header>
                <h3>Address</h3>
            </header>
            <p>
                255 Cremazie ISI<br />

            </p>
            <header>Facebook Link</header>
            <div class="">
                <a href="https://www.facebook.com/AremTechnology?fref=ts"> <img class="img-responsive center-block " src="~/Images/images.jpg" /> </a>
            </div>
        </section>
    </div>
</div>
@section Scripts {
    <script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBTYRuu6Sqqh3AYCahw56_z28rJfBQB7Oc&sensor=true">
</script>

    <script type="text/javascript">
    function initialize() {
        var mapOptions = {
            center: new google.maps.LatLng(45.5440916, -73.6402476),
            zoom: 10
        };
        var map = new google.maps.Map(document.getElementById("map"),
            mapOptions);
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

    }

GestionEcole/GestionEcole/Views/Home/Index.cshtml
@using GestionEcole.Resources.Views.Home;
@using GestionEcole.Resources.Views.Shared;

@{
    ViewBag.Title = Index.Title;
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">

            <div class="row hidden-xs">
                <div class="col-xs-1">
                    &nbsp;
                </div>
                <div class="col-md-8 col-xs-10 text-justify text-warning">
                    <h1 class="text-danger">@Index.h1</h1>
                    <h3 class="text-success">@Index.H3</h3>
                    <p class="">
                        @Index.LoremIpsum
                    </p>
                </div>
                <div class="col-xs-3 hidden-xs hidden-sm">
                    <div class=" col-xs-8 col-xs-offset-2">
                        <ul class="list-group nav nav-tabs nav-stacked text-center" id="menu">
                          
                            <li class="list-group-item-danger">@Html.ActionLink(Index.TeachersLink, "Index", "Enseignant")</li>
                            <li class="list-group-item-info">@Html.ActionLink(Index.StudentsLink, "Index", "Etudiant")</li>
                            <li class="list-group-item-danger">@Html.ActionLink(Index.CoursesLink, "Index", "Matiere")</li>
                            <li class="list-group-item-info">@Html.ActionLink("Contact", "Contact", "Home")</li>
                            @*@if (User.IsInRole("Admin"))
                            {*@
                                <li class="list-group-item-info">@Html.ActionLink(Index.AdministrationLink, "Index", "Administration")</li>
                            @*}*@
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </section>
}

<div class="row col-xs-12 hidden-xs">
    <div class="col-xs-1">
        &nbsp;
    </div>
    <div class="col-md-7 col-xs-10 text-justify text-warning">
        
        <h3 class="text-success">@Index.H3Objectives</h3>

            <p class="">
                @Index.LoremIpsum
            </p>       
    </div>

    <div class="col-md-4 col-xs-12 text-justify text-warning espace">
        <div class="form-group col-md-12 col-md-offset-0 col-xs-8 col-xs-offset-2">
            <img src="~/Images/ecole.gif" class="img-responsive" />
        </div>
        <div>
            &nbsp;
        </div>
        <div class="form-group col-xs-offset-5 col-md-offset-4">

            <a href="https://www.facebook.com/AremTechnology?fref=ts"> <img class="img-responsive " src="~/Images/images.jpg" /> </a>

        </div>

    </div>
</div>