GestionEcole/GestionEcole/Controllers/EvaluationController.cs
using GestionEcole.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionEcole.Controllers
{
    public class EvaluationController : Controller
    {
        private int nbElement = 7;
        private EcoleContainer DB = new EcoleContainer();

        #region Default CRUD
        [Authorize(Roles = "Admin")]
        public ActionResult Index(int numPage = 0)
        {
            var evaluations = (from e in DB.Evaluations
                               select e).ToList();

            var lstPage = (from e in DB.Evaluations
                               select e).OrderBy(ev => ev.EtudiantId).Skip(numPage * nbElement).Take(nbElement).ToList();

            evaluations.GroupBy(g => g.Etudiant.Id).Select(o => new { State = o.Key, evaluations = o.OrderBy(c => c.Etudiant.Nom).ToList() });
            ViewBag.CombienDePage = (from e in DB.Evaluations
                                     select e).Count() / nbElement;

            return View(lstPage);
        }
        [Authorize(Roles = "Admin,Enseignant,Etudiant")]
        public ActionResult Details(int etudiantId, int matiereId, int enseignantId)
        {
            var evaluation = (from e in DB.Evaluations
                              where e.EtudiantId == etudiantId && e.MatiereId == matiereId && e.EnseignantId == enseignantId
                              select e).First();

            return View(evaluation);
        }

        #region Create Region
        [Authorize(Roles = "Admin,Enseignant")]
        public ActionResult Create()
        {
            List<Etudiant> etudiants = (from e in DB.Etudiants
                                        select e).ToList();

            ViewBag.Etudiants = etudiants.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Prenom + " " + e.Nom });

            List<Matiere> matieres = (from m in DB.Matieres
                                      select m).ToList();

            ViewBag.Matieres = matieres.Select(m => new SelectListItem { Value = m.MatiereId.ToString(), Text = m.Titre });

            List<Enseignant> enseignants = (from e in DB.Enseignants
                                            select e).ToList();

            ViewBag.Enseignants = enseignants.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Prenom + " " + e.Nom });

            List<TypeEvaluation> typesEvaluation = (from t in DB.TypeEvaluations
                                                    select t).ToList();

            ViewBag.TypesEvaluation = typesEvaluation.Select(e => new SelectListItem { Value = e.TypeEvaluationId.ToString(), Text = e.Type });

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Enseignant")]
        public ActionResult Create(Evaluation NouvEvaluation)
        {
            try
            {
                DB.Evaluations.Add(NouvEvaluation);

                DB.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region Edit Region

        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult Edit(int etudiantId, int matiereId, int enseignantId)
        {
            var evaluation = (from e in DB.Evaluations
                              where e.EtudiantId == etudiantId && e.MatiereId == matiereId && e.EnseignantId == enseignantId
                              select e).First();

            return View(evaluation);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult Edit(Evaluation EditEvaluation)
        {
            int etudiantId = EditEvaluation.EtudiantId, matiereId = EditEvaluation.MatiereId, enseignantId = EditEvaluation.EnseignantId;

            try
            {
                var evaluation = (from e in DB.Evaluations
                                  where e.EtudiantId == etudiantId && e.MatiereId == matiereId && e.EnseignantId == enseignantId
                                  select e).First();

                evaluation.Note = EditEvaluation.Note;

                DB.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region Delete Region

        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult Delete(int etudiantId, int matiereId, int enseignantId)
        {
            var evaluation = (from e in DB.Evaluations
                              where e.EtudiantId == etudiantId && e.MatiereId == matiereId && e.EnseignantId == enseignantId
                              select e).First();

            return View(evaluation);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult Delete(Evaluation evaluationToBeDeleted)
        {
            int etudiantId = evaluationToBeDeleted.EtudiantId, matiereId = evaluationToBeDeleted.MatiereId, enseignantId = evaluationToBeDeleted.EnseignantId;

            try
            {
                var evaluation = (from e in DB.Evaluations
                                  where e.EtudiantId == etudiantId && e.MatiereId == matiereId && e.EnseignantId == enseignantId
                                  select e).First();

                DB.Evaluations.Remove(evaluation);

                DB.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #endregion

        [Authorize(Roles = "Admin, Enseignant,Etudiant")]
        public ActionResult EvaluationsEtudiant(int etudiantId)
        {
            var evaluations = (from e in DB.Evaluations
                               where e.EtudiantId == etudiantId
                               select e).ToList();

            return View(evaluations);
        }

        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult EvaluationsEnseignantMatiere(int enseignantId, int matiereId)
        {
            var evaluations = (from e in DB.Evaluations
                               where e.EnseignantId == enseignantId && e.MatiereId == matiereId
                               select e).ToList();

            return View(evaluations);
        }

        protected override void Dispose(bool disposing)
        {
            DB.Dispose();
            base.Dispose(disposing);
        }
    }
}

GestionEcole/GestionEcole/Controllers/PresenceCoursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestionEcole.Models;
using System.Web.Script.Serialization;

namespace GestionEcole.Controllers
{

    public class PresenceCoursController : Controller
    {

        private EcoleContainer DB = new EcoleContainer();

        #region Affichage des presences au cours
        //
        // GET: /PresenceCours/

        private int nbElement = 7;
        /// <summary>
        /// Affichage d'une vue selon un certain nombre de presence aux cours par page
        /// </summary>
        /// <param name="numPage">Le numero de page</param>
        /// <returns>La page des cours ordonnees par un certain nombre d'element par pag</returns>
        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult Index(int numPage = 0)
        {
            List<PresenceCours> LstPresCours = (from pc in DB.PresenceCours
                                                select pc).OrderBy(pc => pc.EtudiantId).Skip(nbElement * numPage).Take(nbElement).ToList();

            ViewBag.CombienDePage = (from pc in DB.PresenceCours
                                                select pc).Count() / nbElement;

            return View(LstPresCours);
        }
        #endregion

        #region Detail de presence aux cours
        //
        // GET: /PresenceCours/Details/5
        /// <summary>
        /// Retoure la vue de detail d'une presence au cours
        /// </summary>
        /// <param name="idEtudiant">L'id de l'etudiant</param>
        /// <param name="idCours">L'id d'un cours</param>
        /// <returns>La page de detail d'une presence au cours</returns>
        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult Details(int idEtudiant, int idCours)
        {
            PresenceCours presCours = (from pc in DB.PresenceCours
                                       where pc.EtudiantId == idEtudiant && pc.CoursId == idCours
                                       select pc).First();

            TempData["idCours"] = idCours;

            return View(presCours);
        }
        #endregion

        #region Creation d'une presence au cours
        //
        // GET: /PresenceCours/Create
        /// <summary>
        /// Affichage de la vue de creation d'une presence au cours
        /// </summary>
        /// <returns>La page de creation d'une presence a un cours </returns>
        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult Create()
        {

            IEnumerable<Etudiant> Etudiants = DB.Etudiants.ToList().OrderBy(e => e.Nom);

            ViewBag.Etudiants = Etudiants.Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Nom + " " + e.Prenom });

            IEnumerable<Cours> Cours = DB.Cours.ToList().OrderBy(e => e.DateDebut);

            ViewBag.Cours = Cours.Select(e => new SelectListItem { Value = e.CoursId.ToString(), Text = e.DateDebut.ToString() });

            return View();
        }

        //
        // POST: /PresenceCours/Create
        /// <summary>
        /// Creation d'une presence cours dans la base de donnee
        /// </summary>
        /// <param name="NouvPresCours">Un nouveau cours a creer</param>
        /// <returns> La vue Index des Presences cours si la creation est valider sinon la vue de la creation</returns>
        [HttpPost]
        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult Create(PresenceCours NouvPresCours)
        {
            try
            {
                // TODO: Add insert logic here

                if (ModelState.IsValid)
                {
                    DB.PresenceCours.Add(NouvPresCours);

                    DB.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Inscription aux cours

        // inscription Client 
        /// <summary>
        /// Affichage de la page d'inscription d'un etudiant a un cours
        /// </summary>
        /// <param name="etudiantId">l'id de l'etudiant</param>
        /// <returns>La page d'inscription</returns>
        [Authorize(Roles = "Admin,Etudiant")]
        public ActionResult Inscription(int etudiantId)
        {

            var Etudiant = (from e in DB.Etudiants
                            where e.Id == etudiantId
                            select e).First();

            ViewBag.Etudiant = Etudiant;

            var matieres = DB.Matieres.ToList()
                .OrderBy(e => e.Titre).ToList()
                .Select(m => new SelectListItem { Value = m.MatiereId.ToString(), Text = m.Titre.ToString() });

            ViewBag.matieres = matieres;

            return View(new PresenceCours { EtudiantId = etudiantId, Etudiant = Etudiant });

        }

        //
        // POST: /PresenceCours/Create
        /// <summary>
        /// Inscription d'un etudiant a un cours
        /// </summary>
        /// <param name="NouvPresCours">Le nouveau cours a jouter</param>
        /// <returns>La vue Index des etudiants si l'inscription est valider sinon la vue de l'inscription</returns>
        [HttpPost]
        [Authorize(Roles = "Admin,Etudiant")]
        public ActionResult Inscription(PresenceCours NouvPresCours)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    DB.PresenceCours.Add(NouvPresCours);

                    DB.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch 
            {
                ModelState.AddModelError("", GestionEcole.Resources.Views.PresenceCours.Titles.ErrorMessageCoursInvalid );
                var Etudiant = (from et in DB.Etudiants
                                where et.Id == NouvPresCours.EtudiantId
                                select et).First();

                ViewBag.Etudiant = Etudiant;

                var matieres = DB.Matieres.ToList()
                    .OrderBy(et => et.Titre).ToList()
                    .Select(m => new SelectListItem { Value = m.MatiereId.ToString(), Text = m.Titre.ToString() });

                ViewBag.matieres = matieres;

                return View(new PresenceCours { EtudiantId = NouvPresCours.EtudiantId, Etudiant = Etudiant });
            }
        }

        /// <summary>
        /// Selection d'une matiere dans la page inscription: Utilise Ajax pour l'affichage
        /// </summary>
        /// <param name="idSelect">la matiere a selectionner</param>
        /// <returns>une vue partielle des cours</returns>
        [HttpPost]
        [Authorize(Roles = "Admin, Etudiant")]
        public ActionResult SelectionnerMatiere(string idSelect)
        {
            int idMat = Int32.Parse(idSelect);
            IEnumerable<SelectListItem> lesCours = (from m in DB.Matieres
                                                    where m.MatiereId == idMat
                                                    select m).First().
                                                        Cours.ToList().
                                                        Select(c => new SelectListItem
                                                        {
                                                            Value = c.CoursId.ToString(),
                                                            Text = c.DateDebut.ToLongDateString() +
                                                            " a " +
                                                            c.DateDebut.ToLongTimeString() + " fini le " +
                                                            c.DateFin.ToLongDateString() +
                                                            " a " +
                                                            c.DateFin.ToLongTimeString()
                                                        });

            ViewBag.LesCours = lesCours;
            ViewBag.Etudiant = TempData["etudiant"];
            ViewBag.matieres = TempData["matieres"];

            Etudiant etudiant = ViewBag.Etudiant;

            var Etudiant = (from e in DB.Etudiants
                            where e.Id == etudiant.Id
                            select e).First();

            return PartialView("_CoursPartial", new PresenceCours { EtudiantId = Etudiant.Id, Etudiant = Etudiant });
        }
        #endregion

        #region Edition d'une presence au cours
        //
        // GET: /PresenceCours/Edit/5
        /// <summary>
        /// Edition de la presence de cours
        /// </summary>
        /// <param name="idEtudiant">L'id de l'etudiant</param>
        /// <param name="idCours">L'id du cours</param>
        /// <returns>La page d'Edition d'une presence cours</returns>
        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult Edit(int idEtudiant, int idCours)
        {
            PresenceCours presCours = (from pc in DB.PresenceCours
                                       where pc.EtudiantId == idEtudiant && pc.CoursId == idCours
                                       select pc).First();

            return View(presCours);
        }

        //
        // POST: /PresenceCours/Edit/5
        /// <summary>
        /// Enregistrer une presence au cours dans la base de donnee 
        /// </summary>
        /// <param name="idEtudiant">L'id d'un etudiant</param>
        /// <param name="idCours"></param>
        /// <param name="EditPresCours">La presence au cours a editer</param>

GestionEcole/GestionEcole/Views/Etudiant/Create.cshtml
@using GestionEcole.Resources.Views.Shared
@using GestionEcole.Resources.Views.Etudiant
@model GestionEcole.Models.Etudiant

@{
    ViewBag.Title = Create.ViewBagTitle;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="col-xs-8 col-xs-offset-2">
        <fieldset>
            <legend>@GestionEcole.Resources.Views.Etudiant.Index.ViewBagTitle</legend>

            <div class="form-group col-xs-8 col-xs-offset-2">
                @Html.LabelFor(model => model.Nom, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nom)
            </div>

            <div class="form-group col-xs-8 col-xs-offset-2">
                @Html.LabelFor(model => model.Prenom, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Prenom, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Prenom)
            </div>

            <div class="form-group col-xs-8 col-xs-offset-2">
                @Html.LabelFor(model => model.Email, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>

            <div class="form-group col-xs-8 col-xs-offset-2">
                @Html.LabelFor(model => model.DateNaissance, new { @class = "control-label" })
                <input class="form-control" type="date" name="DateNaissance" id="DateNaissance" />
                @Html.ValidationMessageFor(model => model.DateNaissance)
            </div>

            <div class="form-group col-xs-8 col-xs-offset-2">
                @Html.LabelFor(model => model.Adresse, new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Adresse, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Adresse)
            </div>
        </fieldset>

        <div class="form-group col-xs-12 col-md-8 col-md-offset-2">
            <button class="btn btn-lg btn-primary pull-right" title=@TitreBtn.CreateIcon type="submit"><span class="glyphicon glyphicon-floppy-disk"></span></button>
        </div>
    </div>
}

<div class="col-xs-12">
    <a class="btn btn-lg btn-danger" title=@TitreBtn.BackIcon href="/Etudiant"><span class="glyphicon glyphicon-arrow-left"></span></a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionEcole/GestionEcole/Views/Etudiant/Delete.cshtml
@using GestionEcole.Resources.Views.Shared
@using GestionEcole.Resources.Views.Etudiant
@model GestionEcole.Models.Etudiant

@{
    ViewBag.Title = Delete.ViewBagTitle;
}

<h2>@Delete.ViewBagTitle</h2>

<div class="col-xs-8 col-xs-offset-2">
    <div class="list-group">
        <div class="list-group-item">
            <h4 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Nom)</h4>
            <p class="list-group-item-text">@Html.DisplayFor(model => model.Nom)</p>
        </div>

        <div class="list-group-item">
            <h4 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Prenom)</h4>
            <p class="list-group-item-text">@Html.DisplayFor(model => model.Prenom)</p>
        </div>

        <div class="list-group-item">
            <h4 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Email)</h4>
            <p class="list-group-item-text">@Html.DisplayFor(model => model.Email)</p>
        </div>

        <div class="list-group-item">
            <h4 class="list-group-item-heading">@Html.DisplayNameFor(model => model.DateNaissance)</h4>
            <p class="list-group-item-text">@Html.DisplayFor(model => model.DateNaissance)</p>
        </div>

        <div class="list-group-item">
            <h4 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Adresse)</h4>
            <p class="list-group-item-text">@Html.DisplayFor(model => model.Adresse)</p>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="btn-group btn-group-lg col-xs-12">
        <button type="submit" title=@TitreBtn.DeleteIcon class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
        <a class="btn btn-danger" title=@TitreBtn.BackIcon href="/Etudiant"><span class="glyphicon glyphicon-arrow-left"></span></a>
    </div>
}

GestionEcole/GestionEcole/Views/Etudiant/Details.cshtml
@using GestionEcole.Resources.Views.Shared
@using GestionEcole.Resources.Views.Etudiant
@model GestionEcole.Models.Etudiant

@{
    ViewBag.Title = Details.ViewBagTitle;
    List<GestionEcole.Models.Cours> lesCours = ViewBag.coursEtudiant;
    List<GestionEcole.Models.Matiere> lesMatiere = ViewBag.matiereEtudiant;

    TempData["idEtudiant"] = Model.Id;
}

<h2>
    @ViewBag.Title
    <a class="btn btn-lg btn-default" title=@TitreBtn.EditIcon href="/Etudiant/Edit?id=@Model.Id"><span class="glyphicon glyphicon-pencil"></span></a>
</h2>

<div class="col-xs-8 col-xs-offset-2">
    <div class="list-group">
        <div class="list-group-item">
            <h4 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Nom)</h4>
            <p class="list-group-item-text">@Html.DisplayFor(model => model.Nom)</p>
        </div>

        <div class="list-group-item">
            <h4 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Prenom)</h4>
            <p class="list-group-item-text">@Html.DisplayFor(model => model.Prenom)</p>
        </div>

        <div class="list-group-item">
            <h4 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Email)</h4>
            <p class="list-group-item-text">@Html.DisplayFor(model => model.Email)</p>
        </div>

        <div class="list-group-item">
            <h4 class="list-group-item-heading">@Html.DisplayNameFor(model => model.DateNaissance)</h4>
            <p class="list-group-item-text">@Html.DisplayFor(model => model.DateNaissance)</p>
        </div>

        <div class="list-group-item">
            <h4 class="list-group-item-heading">@Html.DisplayNameFor(model => model.Adresse)</h4>
            <p class="list-group-item-text">@Html.DisplayFor(model => model.Adresse)</p>
        </div>
    </div>
</div>


<fieldset class="col-xs-10 col-xs-offset-1">
    <legend>@Details.LegendStudent @Model.Prenom @Model.Nom :</legend>

    <div>
        @foreach (var item in lesCours)
        {
            <ul class="list-group col-xs-6 col-xs-offset-2">
                <li class="list-group-item">
                    <div>
                        <span class="label label-default col-xs-5">@Details.Course</span> <strong>@item.Matiere.Titre</strong>
                    </div>
                    <div>
                        <span class="label label-default col-xs-5">@Details.LessonsStart</span> <strong>@item.DateDebut</strong>
                    </div>
                    <div>
                        <span class="label label-default col-xs-5">@Details.LessonsEnd</span> <strong>@item.DateFin</strong>
                    </div>
                    <div>
                        <span class="label label-default col-xs-5">@Details.LessonSubject</span> <strong>@item.Description</strong>
                    </div>
                    <div>
                        <span class="label label-default col-xs-5">@Details.Teacher </span> <strong>@item.Enseignant.Nom</strong>
                        <span>@item.Enseignant.Prenom</span>
                    </div>

                </li>

            </ul>
           

        }

    </div>

    <div>
        @Html.ActionLink(@Details.Sinscrire, "Inscription", "PresenceCours", new { etudiantId = Model.Id }, new { @class = "btn  btn-lg btn-info pull-right" })
    </div>


</fieldset>

<fieldset class="col-xs-10 col-xs-offset-1">
    <legend>@Details.LegendCourses @Model.Prenom @Model.Nom : </legend>

    <div class="col-xs-12">
        <div class="list-group col-xs-4 col-xs-offset-4">
            @foreach (var item2 in lesMatiere)
            {
                <div class="list-group-item">
                    <h4 class="list-group-item-heading">Titre</h4>
                    <p class="list-group-item-text">@item2.Titre</p>

                    <h4 class="list-group-item-heading">Description</h4>
                    <p class="list-group-item-text">@item2.Description</p>
                </div>
            }
        </div>
    </div>

</fieldset>

<fieldset class="col-xs-10 col-xs-offset-1">
    <legend>@Details.Average @Model.Prenom @Model.Nom est: @Model.Moyenne %</legend>

    <div class="col-xs-12 col-md-7">
        @Html.ActionLink(@Details.DetailsNotes, "EvaluationsEtudiant", "Evaluation", new { etudiantId = Model.Id }, new { @class = "btn  btn-lg btn-info pull-right" })
    </div>
</fieldset>

<div class="col-xs-12">
    <a class="btn btn-lg btn-danger" title=@TitreBtn.BackIcon href="/Etudiant"><span class="glyphicon glyphicon-arrow-left"></span></a>
</div>

GestionEcole/GestionEcole/Views/Etudiant/Edit.cshtml
@using GestionEcole.Resources.Views.Shared
@using GestionEcole.Resources.Views.Etudiant

@model GestionEcole.Models.Etudiant

@{
    ViewBag.Title = Edit.ViewBagTitle;
}

<h2>@Edit.ViewBagTitle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="col-xs-8 col-xs-offset-2">
        <fieldset>
            <legend>@Edit.Student</legend>

            <div class="form-group col-xs-8 col-xs-offset-2">
                @Html.LabelFor(model => model.Nom, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Nom, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nom)
            </div>

            <div class="form-group col-xs-8 col-xs-offset-2">
                @Html.LabelFor(model => model.Prenom, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Prenom, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Prenom)
            </div>

            <div class="form-group col-xs-8 col-xs-offset-2">
                @Html.LabelFor(model => model.Email, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>

            <div class="form-group col-xs-8 col-xs-offset-2">
                @Html.LabelFor(model => model.DateNaissance, new { @class = "control-label" })
                <input class="form-control" type="date" name="DateNaissance" id="DateNaissance" />
                @Html.ValidationMessageFor(model => model.DateNaissance)
            </div>

            <div class="form-group col-xs-8 col-xs-offset-2">
                @Html.LabelFor(model => model.Adresse, new { @class = "control-label" })
                @Html.TextAreaFor(model => model.Adresse, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Adresse)
            </div>
        </fieldset>

        <div class="form-group col-xs-12 col-md-8 col-md-offset-2">
            <button title=@TitreBtn.SaveIcon class="btn btn-lg btn-primary pull-right" type="submit"><span class="glyphicon glyphicon-floppy-disk"></span></button>
        </div>
    </div>
}

<div class="col-xs-12">
    <a class="btn btn-lg btn-danger" title=@TitreBtn.BackIcon href="/Etudiant"><span class="glyphicon glyphicon-arrow-left"></span></a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestionEcole/GestionEcole/Views/Etudiant/Index.cshtml
@using GestionEcole.Resources.Views.Shared
@using GestionEcole.Resources.Views.Etudiant
@model IEnumerable<GestionEcole.Models.Etudiant>

@{
    ViewBag.Title = Index.ViewBagTitle;
}

<h2>@ViewBag.Title</h2>

<p>
    <a class="btn btn-lg btn-default" title=@TitreBtn.NewIcon href="/Etudiant/Create"><span class="glyphicon glyphicon-plus"></span></a>
</p>

<div class="col-xs-8 col-xs-offset-2">
    <table class="table table-striped table-responsive">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nom)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Prenom)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Prenom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        <div class="btn-group btn-group-lg">
                            <a class="btn btn-default" title=@TitreBtn.EditIcon href="/Etudiant/Edit?id=@item.Id"><span class="glyphicon glyphicon-pencil"></span></a>
                            <a class="btn btn-default" title=@TitreBtn.DetailsIcon href="/Etudiant/Details?id=@item.Id"><span class="glyphicon glyphicon-list"></span></a>
                            <a class="btn btn-default" title=@TitreBtn.DeleteIcon href="/Etudiant/Delete?id=@item.Id"><span class="glyphicon glyphicon-trash"></span></a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>