GestionEcole/GestionEcole/Controllers/CoursController.cs
using GestionEcole.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionEcole.Controllers
{
    
    public class CoursController : Controller
    {
        private int nbElement = 7;
        private EcoleContainer DB = new EcoleContainer();

        #region Default CRUD

        [Authorize(Roles = "Admin")]
        public ActionResult Index(int numPage = 0)
        {
            List<Cours> cours = (from c in DB.Cours
                                 select c).ToList();

            List<Cours> lstPage = (from c in DB.Cours
                                 select c).OrderBy(o => o.CoursId).Skip(nbElement * numPage).Take(nbElement).ToList();

            ViewBag.combienDePage = cours.Count() / nbElement;

            return View(lstPage);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            Cours cours = (from c in DB.Cours
                           where c.CoursId == id
                           select c).First();

            return View(cours);
        }

        #region Create Region

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.Matieres = (from m in DB.Matieres
                                select m).ToList().Select(c => new SelectListItem { Value = c.MatiereId.ToString(), Text = c.Titre });

            var teachers = (from e in DB.Enseignants
                            select e).ToList().Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Prenom + " " + c.Nom });

            ViewBag.Teachers = teachers;

            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(Cours NouvCours)
        {
            try
            {
                
                if (ModelState.IsValid)
                {
                    if (NouvCours.DateDebut.CompareTo(NouvCours.DateFin) < 0)
                    {
                        DB.Cours.Add(NouvCours);

                        DB.SaveChanges();

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Matieres = (from m in DB.Matieres
                                            select m).ToList().Select(c => new SelectListItem { Value = c.MatiereId.ToString(), Text = c.Titre });

                        var teachers = (from e in DB.Enseignants
                                        select e).ToList().Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Prenom + " " + c.Nom });

                        ViewBag.Teachers = teachers;

                        ModelState.AddModelError("", GestionEcole.Resources.Views.Cours.Index.ErrorDate);
                        return View(NouvCours);

                    }
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region Edit Region

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Cours cours = (from c in DB.Cours
                           where c.CoursId == id
                           select c).First();

            return View(cours);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(int id, Cours EditCours)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Cours cours = (from c in DB.Cours
                                   where c.CoursId == id
                                   select c).First();

                    cours.DateDebut = EditCours.DateDebut;
                    cours.DateFin = EditCours.DateFin;
                    cours.Description = EditCours.Description;

                    DB.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region Delete Region

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Cours cours = (from c in DB.Cours
                           where c.CoursId == id
                           select c).First();

            return View(cours);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                Cours cours = (from c in DB.Cours
                               where c.CoursId == id
                               select c).First();

                DB.Cours.Remove(cours);

                DB.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #endregion

        #region Affichage des etudiants d'un cours

        [Authorize(Roles = "Admin, Enseignant")]
        public ActionResult AfficheEtudiantsCours(int coursId)
        {
            var etudiants = (from c in DB.PresenceCours
                             where c.CoursId == coursId
                             select c.Etudiant).ToList();

            ViewBag.leCours = (from c in DB.Cours
                               where c.CoursId == coursId
                               select c).First();

            return View(etudiants);
        }

        #endregion

        protected override void Dispose(bool disposing)
        {
            DB.Dispose();
            base.Dispose(disposing);
        }
    }
}

GestionEcole/GestionEcole/Controllers/MatiereController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestionEcole.Models;

namespace GestionEcole.Controllers
{
    public class MatiereController : Controller
    {
        private EcoleContainer DB = new EcoleContainer();


        #region Affichage de la liste des matieres

        private int nbElement = 7;
        //
        // GET: /Matiere/
        /// <summary>
        ///Affichage d'une vue selon un certain nombre de matiere par page
        /// </summary>
        /// <param name="numPage">Le numero de la page</param>
        /// <returns>une Liste de matiere</returns>
        public ActionResult Index(int numPage = 0)
        {
            List<Matiere> LstMatieres = (from m in DB.Matieres
                                         select m).ToList();

            List<Matiere> LstPage = (from m in DB.Matieres
                                     select m).OrderBy(m => m.MatiereId)
                                         .Skip(numPage * nbElement).
                                         Take(nbElement).ToList();



            ViewBag.CombienDePage = LstMatieres.Count / nbElement;



            return View(LstPage);
        }

        #endregion

        #region Detail de la matiere
        //
        // GET: /Matiere/Details/5
        /// <summary>
        /// Afficher les details d'une matiere donnee
        /// </summary>
        /// <param name="id"> l'id d'une matiere donnee</param>
        /// <returns>La vue de detail d'une matiere</returns>

        public ActionResult Details(int id, int enseignantId = 0)
        {
            Matiere matiere = (from m in DB.Matieres
                               where m.MatiereId == id
                               select m).First();

            // les evaluations dans une matiere

            var typeEval = matiere.Evaluations.Select(i => i.TypeEvaluation).Distinct().ToList();

            ViewBag.typeEval = typeEval;

            var coursMatiere = matiere.Cours.ToList();
            ViewBag.coursMatiere = coursMatiere;

            if (enseignantId != 0)
            {
                List<Cours> lstCours = (from e in DB.Enseignants
                                        where e.Id == enseignantId
                                        select e).First().Cours.ToList();

                List<Cours> lstCoursInMatiere = (from m in lstCours
                                                 where m.MatiereId == id
                                                 select m).ToList();

                ViewBag.lstCoursInMatiere = lstCoursInMatiere;
            }

            return View(matiere);
        }
        #endregion

        #region Creation d'une matiere
        //
        // GET: /Matiere/Create
        /// <summary>
        /// Affiche la page de creation de matiere
        /// </summary>
        /// <returns> La vue de creation de matiere</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Matiere/Create
        /// <summary>
        /// Creation de la matiere dans la base de donnee
        /// </summary>
        /// <param name="NouvMatiere"> La matiere a creer</param>
        /// <returns>la vue Index des matieres si la creation est valider sinon la vue de la creation</returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Matiere NouvMatiere)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    DB.Matieres.Add(NouvMatiere);

                    DB.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Edition d'une matiere
        //
        // GET: /Matiere/Edit/5
        /// <summary>
        /// Edition d'une matiere donnee
        /// </summary>
        /// <param name="id">L'id de la matiere a editer</param>
        /// <returns>Affichage de la vue de l'edition</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Matiere matiere = (from m in DB.Matieres
                               where m.MatiereId == id
                               select m).First();

            return View(matiere);
        }

        //
        // POST: /Matiere/Edit/5
        /// <summary>
        /// Edition d'une matiere et l'enregistrer dans la base de donnees 
        /// </summary>
        /// <param name="id">L'id de la matiere a editer</param>
        /// <param name="EditMatiere">La matiere Editee</param>
        /// <returns>La vue Index des matieres si l'edition est validee sinon la vue de l'edition</returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, Matiere EditMatiere)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    Matiere matiere = (from m in DB.Matieres
                                       where m.MatiereId == id
                                       select m).First();

                    matiere.Titre = EditMatiere.Titre;
                    matiere.Description = EditMatiere.Description;

                    DB.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Suppresssion d'une matiere
        //
        // GET: /Matiere/Delete/5
        /// <summary>
        /// Affichage de la vue de suppression d'une matiere
        /// </summary>
        /// <param name="id">L'id de la matiere a supprimer</param>
        /// <returns>La vue de suppression d'une matiere</returns>
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Matiere matiere = (from m in DB.Matieres
                               where m.MatiereId == id
                               select m).First();

            return View(matiere);
        }

        //
        // POST: /Matiere/Delete/5
        /// <summary>
        /// Suppression de la base de donnee de d'une matiere donnee
        /// </summary>
        /// <param name="id">L'id de la matiere a supprimer</param>
        /// <param name="collection">Le formulaire d'une matiere</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Matiere matiere = (from m in DB.Matieres
                                   where m.MatiereId == id
                                   select m).First();

                DB.Matieres.Remove(matiere);

                DB.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        #endregion



        #region fermeture de page
        protected override void Dispose(bool disposing)
        {
            DB.Dispose();
            base.Dispose(disposing);
        }
        #endregion
    }
}

GestionEcole/GestionEcole/Controllers/TypeEvaluationController.cs
using GestionEcole.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionEcole.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TypeEvaluationController : Controller
    {
        private int nbElement = 7;
        private EcoleContainer DB = new EcoleContainer();

        #region Default CRUD

        public ActionResult Index(int numPage = 0)
        {
            var evaluations = (from t in DB.TypeEvaluations
                               select t).OrderBy(evl => evl.TypeEvaluationId).Skip(numPage * nbElement).Take(nbElement).ToList();

            ViewBag.CombienDePage = (from e in DB.TypeEvaluations
                                     select e).Count() / nbElement;

            return View(evaluations);
        }

        public ActionResult Details(int id)
        {
            var typeEvaluation = (from t in DB.TypeEvaluations
                                  where t.TypeEvaluationId == id
                                  select t).First();

            return View(typeEvaluation);
        }

        #region Create Region

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(TypeEvaluation NouvTypeEvaluation)
        {
            try
            {
                DB.TypeEvaluations.Add(NouvTypeEvaluation);

                DB.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region Edit Region

        public ActionResult Edit(int id)
        {
            var typeEvaluation = (from t in DB.TypeEvaluations
                                  where t.TypeEvaluationId == id
                                  select t).First();

            return View(typeEvaluation);
        }

        [HttpPost]
        public ActionResult Edit(int id, TypeEvaluation EditTypeEvaluation)
        {
            try
            {
                var typeEvaluation = (from t in DB.TypeEvaluations
                                      where t.TypeEvaluationId == id
                                      select t).First();

                typeEvaluation.Type = EditTypeEvaluation.Type;
                typeEvaluation.Ponderation = EditTypeEvaluation.Ponderation;

                DB.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region Delete Region

        public ActionResult Delete(int id)
        {
            var typeEvaluation = (from t in DB.TypeEvaluations
                                  where t.TypeEvaluationId == id
                                  select t).First();

            return View(typeEvaluation);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var typeEvaluation = (from t in DB.TypeEvaluations
                                      where t.TypeEvaluationId == id
                                      select t).First();

                DB.TypeEvaluations.Remove(typeEvaluation);

                DB.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #endregion

        protected override void Dispose(bool disposing)
        {
            DB.Dispose();
            base.Dispose(disposing);
        }
    }
}

GestionEcole/GestionEcole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title Page Users</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="colGris">
    <div id="container" class="container">
        <div class="btn btn-group pull-right">
            <a href="/Langue/FromEnglishToFrench" class="btn btn-default" name="btn_francais"><img class="img-responsive" src="~/Images/france.png" /></a>
            <a href="/Langue/FromFrenchToEnglish" class="btn btn-default" name="btn_anglais"><img class="img-responsive" src="~/Images/united_kingdom.png" /></a>
        </div>
        @Html.Partial("_LoginPartial")
        <div class="visible-xs pull-left col-xs-8">
            <a class="btn btn-lg btn-primary" title=@GestionEcole.Resources.Views.Home.Index.HomeLink href="/Home"><span class="glyphicon glyphicon-home"></span></a>
        </div>
        <img src="~/Images/Banner1.jpg" class="col-xs-12 img-responsive" />

        <div class="col-xs-12" id="header">

            <div class="row">
                <section id="login"></section>
            </div>

            <nav class="navbar navbar-collapse nav-justified bg-danger" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header navbar-btn hidden-xs">
                        <a class="btn btn-lg btn-primary" title=@GestionEcole.Resources.Views.Home.Index.HomeLink href="/Home"><span class="glyphicon glyphicon-home"></span></a>
                    </div>

                    <div class="text-center navbar-left visible-xs ">
                        <ul class="nav navbar-nav btn-group-lg" id="menu">
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Home.Index.TeachersLink, "Index", "Enseignant", new { }, new { @class = " noir btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Home.Index.StudentsLink, "Index", "Etudiant", new { }, new { @class = "noir btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Matiere.Index.TheClasses, "Index", "Matiere", new { }, new { @class = "noir btn-lg" })</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home", new { }, new { @class = "noir btn-lg" })</li>


                        </ul>
                    </div>

                    <div class="col-md-offset-2 col-xs-offset-0 navbar-left hidden-xs">
                        <ul class="nav navbar-nav" id="menu">
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Home.Index.TeachersLink, "Index", "Enseignant", new { }, new { @class = "text-danger btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Home.Index.StudentsLink, "Index", "Etudiant", new { }, new { @class = "text-danger btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Matiere.Index.TheClasses, "Index", "Matiere", new { }, new { @class = "text-danger btn-lg" })</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home", new { }, new { @class = "text-danger btn-lg" })</li>

                        </ul>
                    </div>
                </div>
            </nav>
        </div>

        <div class="col-xs-12 bleuGris" id="body">
            @RenderSection("featured", required: false)

            <section>
                @RenderBody()
            </section>
        </div>


        <div id="footer" class="col-xs-12 text-center  bg-primary">
            <p>&copy; @DateTime.Now.Year - @GestionEcole.Resources.Views.Home.Index.Application</p>

            <h4>Jihene & Cedric</h4>
        </div>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GestionEcole/GestionEcole/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title Page Admins</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="colBeige">
    <div id="container" class="container">
        <div class="btn btn-group pull-right">
            <a href="/Langue/FromEnglishToFrench" class="btn btn-default" name="btn_francais"><img class="img-responsive" src="~/Images/france.png" /></a>
            <a href="/Langue/FromFrenchToEnglish" class="btn btn-default" name="btn_anglais"><img class="img-responsive" src="~/Images/united_kingdom.png" /></a>
        </div>
        @Html.Partial("_LoginPartial")
        <div class="visible-xs pull-left col-xs-8">
            <a class="btn btn-lg btn-primary" title=@GestionEcole.Resources.Views.Home.Index.HomeLink href="/Home"><span class="glyphicon glyphicon-home"></span></a>
        </div>

        <img src="~/Images/admin.jpg" class="col-xs-12 img-responsive" />

        <div class="col-xs-12" id="header">

            <div class="row">
                <section id="login"></section>
            </div>

            <nav class="navbar nav-justified bg-warning" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header navbar-btn hidden-xs">
                        <a class="btn btn-lg btn-primary" title=@GestionEcole.Resources.Views.Home.Index.HomeLink href="/Home"><span class="glyphicon glyphicon-home"></span></a>
                    </div>


                    <div class="text-center navbar-left visible-xs ">
                        <ul class="nav navbar-nav btn-group-lg" id="menu">
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Home.Index.TeachersLink, "Index", "Enseignant", new { }, new { @class = " noir btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Home.Index.StudentsLink, "Index", "Etudiant", new { }, new { @class = "noir btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Matiere.Index.TheClasses, "Index", "Matiere", new { }, new { @class = "noir btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Evaluation.Titles.Index, "Index", "Evaluation", new { }, new { @class = "noir btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.TypeEvaluation.Index.ViewBagTitle, "Index", "TypeEvaluation", new { }, new { @class = "noir btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.PresenceCours.Titles.PresenceCours, "Index", "PresenceCours", new { }, new { @class = "noir btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.PresenceCours.Titles.PresenceCours, "Index", "Cours", new { }, new { @class = "noir btn-lg" })</li>
                            <li>@Html.ActionLink("Administration", "Index", "Administration", new { }, new { @class = "noir btn-lg" })</li>
                        </ul>
                    </div>

                    <div class=" navbar-left hidden-xs">
                        <ul class="nav navbar-nav" id="menu">
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Home.Index.TeachersLink, "Index", "Enseignant", new { }, new { @class = "text-danger btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Home.Index.StudentsLink, "Index", "Etudiant", new { }, new { @class = "text-danger btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Matiere.Index.TheClasses, "Index", "Matiere", new { }, new { @class = "text-danger btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Evaluation.Titles.Index, "Index", "Evaluation", new { }, new { @class = "text-danger btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.TypeEvaluation.Index.ViewBagTitle, "Index", "TypeEvaluation", new { }, new { @class = "text-danger btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.PresenceCours.Titles.PresenceCours, "Index", "PresenceCours", new { }, new { @class = "text-danger btn-lg" })</li>
                            <li>@Html.ActionLink(GestionEcole.Resources.Views.Cours.Index.IndexTitle, "Index", "Cours", new { }, new { @class = "text-danger btn-lg" })</li>
                            <li>@Html.ActionLink("Administration", "Index", "Administration", new { }, new { @class = "text-danger btn-lg" })</li>
                        </ul>
                    </div>

                </div>
            </nav>
        </div>

        <div class="col-xs-12 bg-warning" id="body">
            @RenderSection("featured", required: false)

            <section>
                @RenderBody()
            </section>
        </div>

        @*<div class="col-xs-12 navbar-static-top">*@
        <div id="footer" class="text-center bg-info col-xs-12">
            <p>&copy; @DateTime.Now.Year - @GestionEcole.Resources.Views.Home.Index.Application</p>

            <h4>Jihene & Cedric</h4>
        </div>
        @*</div>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>